insert into soccer_team (country, fifa_code) values
('Russland','RUS'),
('Uruguay','URU'),
('Portugal','POR'),
('Spanien','ESP'),
('Marokko','MAR'),
('Iran','IRN'),
('Frankreich','FRA'),
('Australien','AUS'),
('Peru','PER'),
('Dänemark','DEN'),
('Argentinien','ARG'),
('Island','ISL'),
('Kroatien','CRO'),
('Nigeria','NGA'),
('Brasilien','BRA'),
('Schweiz','SUI'),
('Costa Rica','CRC'),
('Serbien','SRB'),
('Deutschland','GER'),
('Mexiko','MEX'),
('Schweden','SWE'),
('Südkorea','KOR'),
('Belgien','BEL'),
('Panama','PAN'),
('Tunesien','TUN'),
('England','ENG'),
('Polen','POL'),
('Senegal','SEN'),
('Kolumbien','COL'),
('Japan','JPN'),
('Saudi Arabien','KSA'),
('Ägypten','EGY');

Insert into app_user (first_name, last_name) values
('Ulla', 'Brunnbauer'),
('Matthias', 'Brunnbauer'),
('Christian', 'Brunnbauer'),
('Julia', 'Brunnbauer'),
('Benedikt', 'Brunnbauer'),
('Isabella', 'Brandis'),
('Susanne', 'Brunnbauer'),
('Anabel','Brunnbauer'),
('Michael', 'Brunnbauer'),
('Melanie', 'Brunnbauer'),
('Anton', 'Brunnbauer');
